name: Build and Run Rust Project

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Run Script
        run: cargo run --release

      - name: Commit and Push dood.db to 'database' branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b database
          git add dood.db
          git commit -m "Add dood.db database"
          git push https://x-access-token:${PAT_TOKEN}@github.com/Qodri588/api2db.git database
